version: 2

executors:
  machine:
      machine: true

jobs:
  build:
    executor: machine
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: |
          curl -X POST \
          http://localhost/server/health \
          -H 'Cache-Control: no-cache' \
          -H 'Content-Type: application/json' \
          -d '{"hello": "world"}'