version: 2

executors:
  machine:
      machine: true

jobs:
  build:
    executor: machine
    steps:
      - checkout
      - run: bash ./build.sh
      - run: docker-compose images
      - run: docker-compose up -d; sleep 60
      - run: |
          curl -X POST \
          http://localhost/server/health \
          -H 'Cache-Control: no-cache' \
          -H 'Content-Type: application/json' \
          -d '{"hello": "world"}'